logging:
  level:
    ROOT: INFO
server:
  port: 8666

sqlexec.driver: com.mysql.jdbc.Driver
sqlexec.url: jdbc:mysql://127.0.0.1:3306/xvue_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
sqlexec.username: root
sqlexec.password: 123456

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-wait: 10000
    min-idle: 5
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    url: jdbc:mysql://127.0.0.1:3306/xvue_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    validation-query: select 1
  flyway:
    validateOnMigrate: false
    cleanOnValidateError: true
    baseline-on-migrate: true
    placeholderReplacement: false
    table: SCHEMA_VERSION